// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCenter.DAL.Persistent;

#nullable disable

namespace TrainingCenter.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914022603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTrackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTrackId");

                    b.HasIndex("StudentId", "TrainingTrackId")
                        .IsUnique();

                    b.ToTable("Enrollmets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8843),
                            EnrollmentDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 25m,
                            Status = "Active",
                            StudentId = 1,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8845),
                            EnrollmentDate = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 10m,
                            Status = "Active",
                            StudentId = 2,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 15m,
                            Status = "Active",
                            StudentId = 3,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 5m,
                            Status = "Active",
                            StudentId = 4,
                            TrainingTrackId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 0m,
                            Status = "Active",
                            StudentId = 5,
                            TrainingTrackId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 10m,
                            Status = "Active",
                            StudentId = 6,
                            TrainingTrackId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProgressPercentage = 20m,
                            Status = "Active",
                            StudentId = 7,
                            TrainingTrackId = 6
                        });
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Senior .NET Backend Instructor",
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8694),
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = ".NET Backend"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Angular Instructor",
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8697),
                            Email = "sara@example.com",
                            FullName = "Sara Mohamed",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "Angular"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Database Instructor",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.instructor@example.com",
                            FullName = "Omar Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "SQL Server"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "C# Instructor",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.instructor@example.com",
                            FullName = "Mariam Ali",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "C#"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Software Engineering Instructor",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled.instructor@example.com",
                            FullName = "Khaled Mostafa",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "Software Engineering"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Web Development Instructor",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.instructor@example.com",
                            FullName = "Nour Ahmed",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "Web Development"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "ASP.NET Core API Instructor",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yara.instructor@example.com",
                            FullName = "Yara Mohamed",
                            IsActive = true,
                            IsDeleted = false,
                            Specialization = "APIs"
                        });
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8914),
                            EnrollId = 1,
                            IsDeleted = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ReferenceNumber = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3000m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8930),
                            EnrollId = 1,
                            IsDeleted = false,
                            Notes = "Second payment",
                            PaymentDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Visa",
                            ReferenceNumber = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4000m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8934),
                            EnrollId = 2,
                            IsDeleted = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BankTransfer",
                            ReferenceNumber = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2500m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8937),
                            EnrollId = 3,
                            IsDeleted = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "InstaPay",
                            ReferenceNumber = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3000m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8950),
                            EnrollId = 4,
                            IsDeleted = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Visa",
                            ReferenceNumber = new Guid("55555555-5555-5555-5555-555555555555"),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2000m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8954),
                            EnrollId = 5,
                            IsDeleted = false,
                            Notes = "Payment pending",
                            PaymentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ReferenceNumber = new Guid("66666666-6666-6666-6666-666666666666"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 3500m,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8957),
                            EnrollId = 6,
                            IsDeleted = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Mastercard",
                            ReferenceNumber = new Guid("77777777-7777-7777-7777-777777777777"),
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.TrainingTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Code = "DOTNET-BACKEND",
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8738),
                            Description = "Backend development using ASP.NET Core",
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            IsDeleted = false,
                            Level = "Intermediate",
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "ASP.NET Core Backend"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            Code = "ANGULAR-FE",
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8741),
                            Description = "Frontend development using Angular",
                            EndDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            IsDeleted = false,
                            Level = "Intermediate",
                            StartDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "Angular Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Code = "SQL-FUNDAMENTALS",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Database development using SQL Server",
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 3,
                            IsDeleted = false,
                            Level = "Beginner",
                            StartDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "SQL Server Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            Code = "CSHARP-ADVANCED",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced C# programming concepts",
                            EndDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 4,
                            IsDeleted = false,
                            Level = "Advanced",
                            StartDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "Advanced C#"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 25,
                            Code = "SOFTWARE-ENG",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Software engineering principles and practices",
                            EndDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 5,
                            IsDeleted = false,
                            Level = "Intermediate",
                            StartDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "Software Engineering"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 35,
                            Code = "WEB-DEVELOPMENT",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern web development fundamentals",
                            EndDate = new DateTime(2027, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 6,
                            IsDeleted = false,
                            Level = "Beginner",
                            StartDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 25,
                            Code = "ASP-NET-APIS",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Building RESTful APIs using ASP.NET Core",
                            EndDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 7,
                            IsDeleted = false,
                            Level = "Advanced",
                            StartDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "ASP.NET Core APIs"
                        });
                });

            modelBuilder.Entity("TrainingCenter.DAL.presistent.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8505),
                            Email = "ahmed@example.com",
                            FullName = "Ahmed Farag",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01000000000"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 14, 2, 26, 2, 532, DateTimeKind.Utc).AddTicks(8508),
                            Email = "mohamed@example.com",
                            FullName = "Mohamed Ali",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01100000000"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            FullName = "Omar Khaled",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01200000000"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@example.com",
                            FullName = "Youssef Ahmed",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01011111111"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahmoud@example.com",
                            FullName = "Mahmoud Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01122222222"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mostafa@example.com",
                            FullName = "Mostafa Adel",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01233333333"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim@example.com",
                            FullName = "Karim Samir",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "01044444444"
                        });
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Enrollment", b =>
                {
                    b.HasOne("TrainingCenter.DAL.presistent.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingCenter.DAL.Persistent.Models.TrainingTrack", "TrainingTrack")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrainingTrack");
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Payment", b =>
                {
                    b.HasOne("TrainingCenter.DAL.Persistent.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.TrainingTrack", b =>
                {
                    b.HasOne("TrainingCenter.DAL.Persistent.Models.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Enrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("TrainingCenter.DAL.Persistent.Models.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TrainingCenter.DAL.presistent.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
