// <auto-generated />
using System;
using Drill_01_DbContext___First_Migration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drill_01_DbContext___First_Migration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913013910_AddStudentProfile")]
    partial class AddStudentProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@example.com",
                            FullName = "Ahmed Farag",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@example.com",
                            FullName = "Mohamed Ali",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amna@example.com",
                            FullName = "Amna Ali",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentsProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            DateOfBirth = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01012345678",
                            NationalId = 29801011234567L,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            DateOfBirth = new DateTime(1999, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01112345678",
                            NationalId = 29902021234568L,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            DateOfBirth = new DateTime(2000, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01212345678",
                            NationalId = 30003031234569L,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.StudentProfile", b =>
                {
                    b.HasOne("Drill_01_DbContext___First_Migration.Models.Student", "Student")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Drill_01_DbContext___First_Migration.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Student", b =>
                {
                    b.Navigation("StudentProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
