// <auto-generated />
using System;
using Drill_01_DbContext___First_Migration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drill_01_DbContext___First_Migration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913035838_AddPaymentSummary")]
    partial class AddPaymentSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("StudentId", "TrackId")
                        .IsUnique()
                        .HasFilter("[Status] = 'Active'");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 92.5m,
                            Status = "Active",
                            StudentId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 0m,
                            Status = "Pending",
                            StudentId = 1,
                            TrackId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 88.0m,
                            Status = "Completed",
                            StudentId = 2,
                            TrackId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 85.5m,
                            Status = "Active",
                            StudentId = 2,
                            TrackId = 3
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 95.0m,
                            Status = "Completed",
                            StudentId = 3,
                            TrackId = 3
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mohamed.ali@example.com",
                            FullName = "Mohamed Ali"
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PaymentSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentId = 1,
                            PaymentStatus = "Paid",
                            TotalPaid = 10000m,
                            TotalRequired = 10000m
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentId = 2,
                            PaymentStatus = "PartiallyPaid",
                            TotalPaid = 4000m,
                            TotalRequired = 12000m
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentId = 3,
                            PaymentStatus = "Pending",
                            TotalPaid = 0m,
                            TotalRequired = 10000m
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentId = 4,
                            PaymentStatus = "PartiallyPaid",
                            TotalPaid = 7500m,
                            TotalRequired = 15000m
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentId = 5,
                            PaymentStatus = "Paid",
                            TotalPaid = 15000m,
                            TotalRequired = 15000m
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@example.com",
                            FullName = "Ahmed Farag",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@example.com",
                            FullName = "Mohamed Ali",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amna@example.com",
                            FullName = "Amna Ali",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentsProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            DateOfBirth = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01012345678",
                            NationalId = 29801011234567L,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            DateOfBirth = new DateTime(1999, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01112345678",
                            NationalId = 29902021234568L,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            DateOfBirth = new DateTime(2000, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01212345678",
                            NationalId = 30003031234569L,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.TrainingTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Backend development using ASP.NET Core",
                            InstructorId = 1,
                            Name = "ASP.NET Backend"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Frontend development using Angular",
                            InstructorId = 1,
                            Name = "Angular Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full Stack development using .NET and Angular",
                            InstructorId = 2,
                            Name = "Full Stack .NET"
                        });
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Enrollment", b =>
                {
                    b.HasOne("Drill_01_DbContext___First_Migration.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drill_01_DbContext___First_Migration.Models.TrainingTrack", "Track")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.PaymentSummary", b =>
                {
                    b.HasOne("Drill_01_DbContext___First_Migration.Models.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("Drill_01_DbContext___First_Migration.Models.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.StudentProfile", b =>
                {
                    b.HasOne("Drill_01_DbContext___First_Migration.Models.Student", "Student")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Drill_01_DbContext___First_Migration.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.TrainingTrack", b =>
                {
                    b.HasOne("Drill_01_DbContext___First_Migration.Models.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("Drill_01_DbContext___First_Migration.Models.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
